/* One small pixel drawing per installed pack, 12 by 12. Drawn in ink on
   paper with one terracotta accent, so they read as part of the notice.
   Rows: '.' empty, '#' ink, 'r' red terracotta, 'y' yellow terracotta. */

export const GLYPH_SIZE = 12;

export const PACK_GLYPHS: Record<string, readonly string[]> = {
  /* one per category, so no pack ever falls back to a bare chest */
  'Hamar': [
    '.....#####..',
    '....#######.',
    '....#######.',
    '.....#####..',
    '.......y....',
    '.......y....',
    '......y.....',
    '......y.....',
    '.....y......',
    '.....y......',
    '....y.......',
    '............',
  ],
  'Skjöldur': [
    '.##########.',
    '#rrrrrrrrrr#',
    '#rrr####rrr#',
    '#rr######rr#',
    '#rrr####rrr#',
    '#rrrrrrrrrr#',
    '.#rrrrrrrr#.',
    '..#rrrrrr#..',
    '...#rrrr#...',
    '....#rr#....',
    '.....##.....',
    '............',
  ],
  'Epli': [
    '.....##.....',
    '....##......',
    '...######...',
    '..rrrrrrrr..',
    '.rrrrrrrrrr.',
    'rrrrrrrrrrrr',
    'rrrrrrrrrrrr',
    'rrrrrrrrrrrr',
    '.rrrrrrrrrr.',
    '..rrrrrrrr..',
    '...rr..rr...',
    '............',
  ],
  'Tannhjól': [
    '..#..##..#..',
    '..##.##.##..',
    '.###yyyy###.',
    '..yyyyyyyy..',
    '..yy#..#yy..',
    '..yy....yy..',
    '..yy#..#yy..',
    '..yyyyyyyy..',
    '.###yyyy###.',
    '..##.##.##..',
    '..#..##..#..',
    '............',
  ],
  'Turn': [
    '#.#.#.#.#.#.',
    '############',
    '#..........#',
    '#..######..#',
    '#..#....#..#',
    '#..#....#..#',
    '#..######..#',
    '#..........#',
    '############',
    '#...####...#',
    '#...#..#...#',
    '#...#..#...#',
  ],
  'Talblaðra': [
    '.##########.',
    '#..........#',
    '#.rr.rr.rr.#',
    '#..........#',
    '#..........#',
    '.##########.',
    '...##.......',
    '..##........',
    '.##.........',
    '............',
    '............',
    '............',
  ],
  'Smaragður': [
    '....####....',
    '..##rrrr##..',
    '.#rrrrrrrr#.',
    '#rrrrrrrrrr#',
    '#rrr####rrr#',
    '#rr#....#rr#',
    '#rr#....#rr#',
    '#rrr####rrr#',
    '#rrrrrrrrrr#',
    '.#rrrrrrrr#.',
    '..##rrrr##..',
    '....####....',
  ],
  'Steðji': [
    '..########..',
    '..########..',
    '...######...',
    '....####....',
    '...######...',
    '..########..',
    '.##########.',
    '.##########.',
    '....####....',
    '...######...',
    '..########..',
    '............',
  ],
  'Tré': [
    '....####....',
    '...######...',
    '..########..',
    '.##########.',
    '..########..',
    '...######...',
    '....####....',
    '.....##.....',
    '.....##.....',
    '....yyyy....',
    '...yyyyyy...',
    '............',
  ],
  'Herobrine': [
    '############',
    '#..........#',
    '#.##....##.#',
    '#.##....##.#',
    '#..........#',
    '#..........#',
    '#...####...#',
    '#..........#',
    '#.########.#',
    '#..........#',
    '############',
    '............',
  ],
  /* generic labels a pack can be given in the admin panel */
  'Kista': [
    '............',
    '.##########.',
    '#..........#',
    '#..........#',
    '############',
    '#....rr....#',
    '#....rr....#',
    '#..........#',
    '#..........#',
    '#..........#',
    '.##########.',
    '............',
  ],
  'Sverð': [
    '..........##',
    '.........###',
    '........###.',
    '.......###..',
    '......###...',
    '.yy..###....',
    '..yy###.....',
    '...yyy......',
    '..yyyy......',
    '.yy.yy......',
    'yy...y......',
    '............',
  ],
  'Bók': [
    '............',
    '.#########..',
    '.#rrrrrrr#..',
    '.#rrrrrrr##.',
    '.#rrrrrrr.#.',
    '.#rrrrrrr.#.',
    '.#rrrrrrr.#.',
    '.#rrrrrrr.#.',
    '.#rrrrrrr##.',
    '.#########..',
    '............',
    '............',
  ],
  'Stjarna': [
    '.....yy.....',
    '.....yy.....',
    '....yyyy....',
    '....yyyy....',
    'yyyyyyyyyyyy',
    '.yyyyyyyyyy.',
    '..yyyyyyyy..',
    '...yyyyyy...',
    '..yyy..yyy..',
    '.yy......yy.',
    'y..........y',
    '............',
  ],
  'Hús': [
    '.....##.....',
    '....#rr#....',
    '...#rrrr#...',
    '..#rrrrrr#..',
    '.#rrrrrrrr#.',
    '############',
    '.#........#.',
    '.#.yy..##.#.',
    '.#.yy..##.#.',
    '.#.....##.#.',
    '.#.....##.#.',
    '.##########.',
  ],
  'Merki JOÐ': [
    '############',
    '#..........#',
    '#..#####...#',
    '#.....#....#',
    '#.....#....#',
    '#.....#....#',
    '#.....#....#',
    '#.#...#....#',
    '#.#...#....#',
    '#..###.....#',
    '#..........#',
    '############',
  ],
  /* MVP: a framed painting */
  'MVP': [
    '############',
    '#..........#',
    '#.yyyy.....#',
    '#.yyyy..rr.#',
    '#.......rr.#',
    '#..........#',
    '#....##....#',
    '#...####...#',
    '#..######..#',
    '#.########.#',
    '#..........#',
    '############',
  ],
  /* Banner Flags: a flag on a pole */
  'Banner Flags': [
    '##..........',
    '##rrrrrrrr..',
    '##rrrrrrrrr.',
    '##rryyrrrrrr',
    '##rryyrrrrr.',
    '##rrrrrrrr..',
    '##rrrrrrr...',
    '##..........',
    '##..........',
    '##..........',
    '##..........',
    '##..........',
  ],
  /* Call of the King: a crown */
  'Call of the King': [
    '............',
    '............',
    'y....yy....y',
    'yy...yy...yy',
    'yyy.yyyy.yyy',
    'yyyyyyyyyyyy',
    'yyyyyyyyyyyy',
    'yyyrryyrryyy',
    'yyyrryyrryyy',
    'yyyyyyyyyyyy',
    '############',
    '............',
  ],
  /* Colored Name Teams: a name tag on a string */
  'Colored Name Teams': [
    '.....#......',
    '.....#......',
    '....###.....',
    '.##########.',
    '#..........#',
    '#.rr.####..#',
    '#.rr.......#',
    '#....######.',
    '#..........#',
    '.##########.',
    '............',
    '............',
  ],
  /* Dungeons & Taverns: a tankard */
  'Dungeons & Taverns': [
    '............',
    '..yyyyyyy...',
    '.#########..',
    '.#.......#..',
    '.#.......###',
    '.#.......#.#',
    '.#.......#.#',
    '.#.......#.#',
    '.#.......###',
    '.#.......#..',
    '.#########..',
    '............',
  ],
  /* Ghast Mayhem: a ghast with tentacles */
  'Ghast Mayhem': [
    '.##########.',
    '#..........#',
    '#..##..##..#',
    '#..##..##..#',
    '#..........#',
    '#...rrrr...#',
    '#..........#',
    '.##########.',
    '.#..#..#..#.',
    '.#..#..#..#.',
    '....#..#....',
    '............',
  ],
  /* Holographic Tags: a floating label with rays */
  'Holographic Tags': [
    '............',
    '.#........#.',
    '..#......#..',
    '...######...',
    '..#......#..',
    '..#.rrrr.#..',
    '..#......#..',
    '...######...',
    '..#......#..',
    '.#........#.',
    '............',
    '............',
  ],
  /* LY Graves: a headstone */
  'LY Graves': [
    '............',
    '....####....',
    '...######...',
    '..########..',
    '..##.rr.##..',
    '..##rrrr##..',
    '..##.rr.##..',
    '..##.rr.##..',
    '..########..',
    '..########..',
    '.##########.',
    '############',
  ],
  /* Show Player Health: a heart */
  'Show Player Health': [
    '............',
    '.###....###.',
    '#rrr#..#rrr#',
    '#rrrr##rrrr#',
    '#rrrrrrrrrr#',
    '#rrrrrrrrrr#',
    '.#rrrrrrrr#.',
    '..#rrrrrr#..',
    '...#rrrr#...',
    '....#rr#....',
    '.....##.....',
    '............',
  ],
  /* Better Mineshaft: a pickaxe */
  'Better Mineshaft': [
    '.......####.',
    '.....##...##',
    '....#......#',
    '...#.......#',
    '..##........',
    '.####.......',
    '##.##.......',
    '#...........',
    '...yy.......',
    '..yy........',
    '.yy.........',
    'yy..........',
  ],
  /* MC Paint: a brush with a red tip */
  'MC Paint': [
    '..........yy',
    '.........yyy',
    '........yyy.',
    '.......yyy..',
    '......yyy...',
    '.....###....',
    '....####....',
    '...#####....',
    '..rrr##.....',
    '.rrrrr......',
    'rrrrr.......',
    '.rrr........',
  ],
  /* Waystones: a standing stone */
  'Waystones': [
    '............',
    '....####....',
    '...######...',
    '...##rr##...',
    '...#rrrr#...',
    '...##rr##...',
    '...######...',
    '...######...',
    '...######...',
    '..########..',
    '.##########.',
    '############',
  ],
  /* Vanilla Refresh: a crafting grid */
  'Vanilla Refresh': [
    '############',
    '#...#...#..#',
    '#.y.#.y.#..#',
    '#...#...#..#',
    '############',
    '#...#...#..#',
    '#...#.r.#..#',
    '#...#...#..#',
    '############',
    '#...#...#..#',
    '#...#...#..#',
    '############',
  ],
  /* Wabi-Sabi Structures: a torii gate */
  'Wabi-Sabi Structures': [
    'rrrrrrrrrrrr',
    '.rrrrrrrrrr.',
    '..rr....rr..',
    '.rrrrrrrrrr.',
    '..rr....rr..',
    '..rr....rr..',
    '..rr....rr..',
    '..rr....rr..',
    '..rr....rr..',
    '..rr....rr..',
    '.###....###.',
    '............',
  ],
};

/** The generic labels, offered as choices in the admin panel. */
export const GENERIC_GLYPHS = [
  'Kista', 'Sverð', 'Bók', 'Stjarna', 'Hús', 'Merki JOÐ',
  'Hamar', 'Skjöldur', 'Epli', 'Tannhjól', 'Turn', 'Talblaðra', 'Smaragður', 'Steðji', 'Tré',
] as const;

/** Every category has a drawing, so a pack without its own still gets a real icon. */
const CATEGORY_GLYPH: Record<string, string> = {
  BUILD: 'Hamar', COMBAT: 'Skjöldur', SURVIVAL: 'Epli', QOL: 'Tannhjól',
  STRUCTURE: 'Turn', SOCIAL: 'Talblaðra', LOOT: 'Kista', TRADE: 'Smaragður',
  CRAFT: 'Steðji', WORLD: 'Tré',
};

/** The drawing for a pack: the one it was given, else one drawn for its name, else its category's. */
export function glyphFor(pack: { name: string; glyph?: string | null; category?: string }): readonly string[] {
  if (pack.glyph && PACK_GLYPHS[pack.glyph]) return PACK_GLYPHS[pack.glyph];
  if (PACK_GLYPHS[pack.name]) return PACK_GLYPHS[pack.name];
  return PACK_GLYPHS[CATEGORY_GLYPH[(pack.category ?? '').toUpperCase()] ?? 'Kista'];
}
