/* One small pixel drawing per installed pack, 12 by 12. Drawn in ink on
   paper with one terracotta accent, so they read as part of the notice.
   Rows: '.' empty, '#' ink, 'r' red terracotta, 'y' yellow terracotta. */

export const GLYPH_SIZE = 12;

export const PACK_GLYPHS: Record<string, readonly string[]> = {
  /* MVP: a framed painting */
  'MVP': [
    '############',
    '#..........#',
    '#.yyyy.....#',
    '#.yyyy..rr.#',
    '#.......rr.#',
    '#..........#',
    '#....##....#',
    '#...####...#',
    '#..######..#',
    '#.########.#',
    '#..........#',
    '############',
  ],
  /* Banner Flags: a flag on a pole */
  'Banner Flags': [
    '##..........',
    '##rrrrrrrr..',
    '##rrrrrrrrr.',
    '##rryyrrrrrr',
    '##rryyrrrrr.',
    '##rrrrrrrr..',
    '##rrrrrrr...',
    '##..........',
    '##..........',
    '##..........',
    '##..........',
    '##..........',
  ],
  /* Call of the King: a crown */
  'Call of the King': [
    '............',
    '............',
    'y....yy....y',
    'yy...yy...yy',
    'yyy.yyyy.yyy',
    'yyyyyyyyyyyy',
    'yyyyyyyyyyyy',
    'yyyrryyrryyy',
    'yyyrryyrryyy',
    'yyyyyyyyyyyy',
    '############',
    '............',
  ],
  /* Colored Name Teams: a name tag on a string */
  'Colored Name Teams': [
    '.....#......',
    '.....#......',
    '....###.....',
    '.##########.',
    '#..........#',
    '#.rr.####..#',
    '#.rr.......#',
    '#....######.',
    '#..........#',
    '.##########.',
    '............',
    '............',
  ],
  /* Dungeons & Taverns: a tankard */
  'Dungeons & Taverns': [
    '............',
    '..yyyyyyy...',
    '.#########..',
    '.#.......#..',
    '.#.......###',
    '.#.......#.#',
    '.#.......#.#',
    '.#.......#.#',
    '.#.......###',
    '.#.......#..',
    '.#########..',
    '............',
  ],
  /* Ghast Mayhem: a ghast with tentacles */
  'Ghast Mayhem': [
    '.##########.',
    '#..........#',
    '#..##..##..#',
    '#..##..##..#',
    '#..........#',
    '#...rrrr...#',
    '#..........#',
    '.##########.',
    '.#..#..#..#.',
    '.#..#..#..#.',
    '....#..#....',
    '............',
  ],
  /* Holographic Tags: a floating label with rays */
  'Holographic Tags': [
    '............',
    '.#........#.',
    '..#......#..',
    '...######...',
    '..#......#..',
    '..#.rrrr.#..',
    '..#......#..',
    '...######...',
    '..#......#..',
    '.#........#.',
    '............',
    '............',
  ],
  /* LY Graves: a headstone */
  'LY Graves': [
    '............',
    '....####....',
    '...######...',
    '..########..',
    '..##.rr.##..',
    '..##rrrr##..',
    '..##.rr.##..',
    '..##.rr.##..',
    '..########..',
    '..########..',
    '.##########.',
    '############',
  ],
  /* Show Player Health: a heart */
  'Show Player Health': [
    '............',
    '.###....###.',
    '#rrr#..#rrr#',
    '#rrrr##rrrr#',
    '#rrrrrrrrrr#',
    '#rrrrrrrrrr#',
    '.#rrrrrrrr#.',
    '..#rrrrrr#..',
    '...#rrrr#...',
    '....#rr#....',
    '.....##.....',
    '............',
  ],
  /* Better Mineshaft: a pickaxe */
  'Better Mineshaft': [
    '.......####.',
    '.....##...##',
    '....#......#',
    '...#.......#',
    '..##........',
    '.####.......',
    '##.##.......',
    '#...........',
    '...yy.......',
    '..yy........',
    '.yy.........',
    'yy..........',
  ],
  /* MC Paint: a brush with a red tip */
  'MC Paint': [
    '..........yy',
    '.........yyy',
    '........yyy.',
    '.......yyy..',
    '......yyy...',
    '.....###....',
    '....####....',
    '...#####....',
    '..rrr##.....',
    '.rrrrr......',
    'rrrrr.......',
    '.rrr........',
  ],
  /* Waystones: a standing stone */
  'Waystones': [
    '............',
    '....####....',
    '...######...',
    '...##rr##...',
    '...#rrrr#...',
    '...##rr##...',
    '...######...',
    '...######...',
    '...######...',
    '..########..',
    '.##########.',
    '############',
  ],
  /* Vanilla Refresh: a crafting grid */
  'Vanilla Refresh': [
    '############',
    '#...#...#..#',
    '#.y.#.y.#..#',
    '#...#...#..#',
    '############',
    '#...#...#..#',
    '#...#.r.#..#',
    '#...#...#..#',
    '############',
    '#...#...#..#',
    '#...#...#..#',
    '############',
  ],
  /* Wabi-Sabi Structures: a torii gate */
  'Wabi-Sabi Structures': [
    'rrrrrrrrrrrr',
    '.rrrrrrrrrr.',
    '..rr....rr..',
    '.rrrrrrrrrr.',
    '..rr....rr..',
    '..rr....rr..',
    '..rr....rr..',
    '..rr....rr..',
    '..rr....rr..',
    '..rr....rr..',
    '.###....###.',
    '............',
  ],
};
