// ─────────────────────────────────────────────────────────────────────────────
// Datapack awareness
//
// A resource-pack asset is USED if a datapack invokes it. Datapacks reach RP
// assets through data components:
//   • minecraft:item_model         → an item-model id  → assets/<ns>/items/<id>.json
//   • minecraft:custom_model_data   → resolved THROUGH the base item's model
//   • text components with "font"   → assets/<ns>/font/<name>.json
//
// We scan .mcfunction commands, loot tables, item modifiers, recipes, and
// advancement icons. Extraction is best-effort by design: NBT built by macros
// or generated by plugins cannot be seen statically, and we say so in the report
// rather than pretending certainty.
// ─────────────────────────────────────────────────────────────────────────────

import type { DatapackInput, DatapackRef } from './types';

const ITEM_MODEL_RE = /(?:minecraft:)?item_model\s*[=:]\s*"?([a-z0-9_.-]+:[a-z0-9_./-]+|[a-z0-9_./-]+)"?/gi;
// JSON text components quote the key; SNBT components (tellraw, item names) may
// not quote either side — accept both.
const FONT_RE = /"?font"?\s*:\s*["']?([a-z0-9_.-]+:[a-z0-9_./-]+|[a-z0-9_./-]+)["']?/gi;
// custom_model_data as a component: int (legacy) or object (1.21.4+).
const CMD_INT_RE = /(?:minecraft:)?custom_model_data\s*[=:]\s*(\d+)\b/gi;
const CMD_OBJ_RE = /(?:minecraft:)?custom_model_data\s*[=:]\s*\{/gi;
// Base item preceding a component block: `minecraft:diamond_sword[` or
// `music_disc_13[` — item ids can contain digits.
const ITEM_WITH_COMPONENTS_RE = /\b(?:minecraft:)?([a-z0-9_]+)\s*\[/gi;

/** A single deduped external reference plus its provenance. */
export interface ExtractedRefs {
  refs: DatapackRef[];
  /** Files scanned per pack, for the coverage report. */
  scanned: Record<string, number>;
}

function isDatapackFile(path: string): boolean {
  return /(^|\/)data\//.test(path);
}

function fileCategory(path: string): string | null {
  const p = path.toLowerCase();
  if (p.endsWith('.mcfunction')) return 'function';
  if (/\/loot_tables?\/.+\.json$/.test(p)) return 'loot_table';
  if (/\/item_modifiers?\/.+\.json$/.test(p)) return 'item_modifier';
  if (/\/recipes?\/.+\.json$/.test(p)) return 'recipe';
  if (/\/advancements?\/.+\.json$/.test(p)) return 'advancement';
  if (/\/predicates?\/.+\.json$/.test(p)) return 'predicate';
  return null;
}

/** Pull the base item id that a component block hangs off of, nearest before `idx`. */
function baseItemBefore(text: string, idx: number): string | undefined {
  const slice = text.slice(Math.max(0, idx - 80), idx + 1);
  let last: string | undefined;
  let m: RegExpExecArray | null;
  ITEM_WITH_COMPONENTS_RE.lastIndex = 0;
  while ((m = ITEM_WITH_COMPONENTS_RE.exec(slice))) last = m[1];
  return last;
}

function scanText(text: string, pack: string, file: string, out: DatapackRef[]) {
  let m: RegExpExecArray | null;

  ITEM_MODEL_RE.lastIndex = 0;
  while ((m = ITEM_MODEL_RE.exec(text))) {
    out.push({ pack, file, via: 'item_model', value: m[1] });
  }

  FONT_RE.lastIndex = 0;
  while ((m = FONT_RE.exec(text))) {
    // Skip the well-known vanilla fonts referenced in text — still record, the
    // resolver will decide (a pack may legitimately override default/alt).
    out.push({ pack, file, via: 'font', value: m[1] });
  }

  CMD_INT_RE.lastIndex = 0;
  while ((m = CMD_INT_RE.exec(text))) {
    const base = baseItemBefore(text, m.index);
    out.push({ pack, file, via: 'custom_model_data', value: m[1], context: base });
  }

  CMD_OBJ_RE.lastIndex = 0;
  while ((m = CMD_OBJ_RE.exec(text))) {
    const base = baseItemBefore(text, m.index);
    // For the object form we cannot cheaply parse the SNBT; record presence so
    // the report flags that this item drives a model dispatch we can't fully see.
    out.push({ pack, file, via: 'custom_model_data', value: '(object)', context: base });
  }
}

/** Walk a parsed JSON tree collecting item_model / font / custom_model_data. */
function scanJson(node: any, pack: string, file: string, out: DatapackRef[], depth = 0) {
  if (!node || depth > 60) return;
  if (Array.isArray(node)) { node.forEach((n) => scanJson(n, pack, file, out, depth + 1)); return; }
  if (typeof node !== 'object') return;
  for (const [key, value] of Object.entries(node)) {
    const bare = key.replace(/^minecraft:/, '');
    if (bare === 'item_model' && typeof value === 'string') {
      out.push({ pack, file, via: 'item_model', value });
    } else if (bare === 'font' && typeof value === 'string') {
      out.push({ pack, file, via: 'font', value });
    } else if (bare === 'custom_model_data') {
      if (typeof value === 'number') out.push({ pack, file, via: 'custom_model_data', value: String(value) });
      else out.push({ pack, file, via: 'custom_model_data', value: '(object)' });
    } else {
      scanJson(value, pack, file, out, depth + 1);
    }
  }
}

export function extractDatapackRefs(datapacks: DatapackInput[]): ExtractedRefs {
  const refs: DatapackRef[] = [];
  const scanned: Record<string, number> = {};
  for (const dp of datapacks) {
    let count = 0;
    for (const f of dp.files) {
      if (!isDatapackFile(f.path)) continue;
      const cat = fileCategory(f.path);
      if (!cat || f.text == null) continue;
      count++;
      if (cat === 'function') {
        scanText(f.text, dp.label, f.path, refs);
      } else {
        try {
          scanJson(JSON.parse(f.text), dp.label, f.path, refs);
        } catch {
          // Malformed datapack JSON — scan as raw text so we still catch refs.
          scanText(f.text, dp.label, f.path, refs);
        }
      }
    }
    scanned[dp.label] = count;
  }
  // Dedupe identical (via,value,file) tuples.
  const seen = new Set<string>();
  const deduped = refs.filter((r) => {
    const k = `${r.via}|${r.value}|${r.file}|${r.context ?? ''}`;
    if (seen.has(k)) return false;
    seen.add(k);
    return true;
  });
  return { refs: deduped, scanned };
}
